name: Build
 
on:
  push:
    branches: [ master ]
 
jobs:
  build-standalone:
   strategy:
    matrix: 
     unity: ['2020.1.3f1']
     editorPath: ['C:\Opt\UnityEditor\2020.1.3f1\Editor\Unity.exe']
     projectPath: ['.\actions-runner\_work\OVRSandbox\OVRSandbox']

   runs-on: self-hosted 
   steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        clean: false
 
  build-quest:
   strategy:
    matrix: 
     unity: ['2020.1.3f1']
     editorPath: ['C:\Opt\UnityEditor\2020.1.3f1\Editor\Unity.exe']
     projectPath: ['.\actions-runner\_work\OVRSandbox\OVRSandbox']

   runs-on: self-hosted 
   steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        clean: false
 
    - name: Build For Standalone
      run: |
         & ${{ matrix.editorPath }} -quit -batchmode -projectPath ${{ matrix.projectPath }} -executeMethod ApplicationBuild.BuildStandAlone -buildTarget Standalone -nographics -logFile - | Out-Host
    - uses: actions/upload-artifact@v1
      with:
       name: OVRSandboxStandalone_${{github.run_number}}
       path: .\Build\Standalone
    - name: Build For Quest
      run: |
         & ${{ matrix.editorPath }} -quit -batchmode -projectPath ${{ matrix.projectPath}} -executeMethod ApplicationBuild.BuildQuest -buildTarget Android -nographics -logFile - | Out-Host
    #- name: Release
    #  run: Copy-Item .\actions-runner\_work\OVRSandbox\OVRSandbox\Build D:\Builds\OVRSandbox${{github.run_number}}
    - uses: actions/upload-artifact@v1
      with:
       name: OVRSandboxQuest_${{github.run_number}}
       path: .\Build\Quest
    
